### ISSUE TITLE
Cant run npm install

### ISSUE THREAD

**Issue by timothymarois** [chunghha/nuxt-daisy#1]
Looks like from the current state of download of this repo, running `npm install` from out of box. fails 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: nuxt-daisy@0.1.0
npm ERR! Found: vue@3.2.45
```

more related to error 

```
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.24
````

**Comment by timothymarois** [comment]
Ok, looks like you're missing `"vue": "^3.2.25"` from the package, if this is a starter kit, it should include vue3 in deps.

**Comment by chunghha** [comment]
I am sorry for taking too while to reply. There are many updates since then. Please try the latest.
