### ISSUE TITLE
defineNuxtConfig error

### ISSUE THREAD

**Issue by kero13ro** [chunghha/nuxt-daisy#2]
nuxt crashed silently in 3.4.2
``` 
export default {
  buildModules: ['@nuxtjs/tailwindcss']
}
```
nuxt.config fixed version
```
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss']
})

```

**Comment by chunghha** [comment]
I am sorry for my late response. As I am away from using Nuxt nowadays I am not updating this repo often. However, the commit I just made fixes this problem.
